name: iOS Build
on:
  push:
    branches: ['master']
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    name: iOS Build
    permissions: write-all
    runs-on: macos-15
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@master
        with:
          xcode-version: '16.4'
      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v4
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-ios
          path: |
            .haxelib/
            export/release/ios/dustin/haxe/
          restore-keys: |
            cache-build-ios
      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s
      - name: Building the game
        run: haxelib run lime build ios -nosign -final
      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-ios") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Making ipa file
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/dustin.app
          ldid -S../../../dustin/dustin.entitlements dustin
          cd ..
          mkdir Payload
          mv dustin.app Payload
          zip -r dustin.ipa Payload
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Dustin iOS
          path: export/release/ios/build/Release-iphoneos/*.ipa
      - name: Uploading new cache
        uses: actions/cache@v4
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-ios
          path: |
            .haxelib/
            export/release/ios/dustin/haxe/
          restore-keys: |
            cache-build-ios
